### ISSUE TITLE
Handle Tie

### ISSUE THREAD

**Issue by JakeHartnell** [1337-Society/blotto#3]
In a tie, everyone should get their money back, this is unlikely to happen, but possible. : )

Be sure to write tests.

**Comment by 0xJayak** [comment]
Design decisions I did in my PR linked above - please review if this is the way we'd like to go. For each of them there is test in the PR:

* If battlefield turn ends with a tie on stakes and also the overall game ends with a tie on victory points ... no victory points and prize pool saved. All participating players are able to withdraw the amount they staked, no prize pool additions.
* If a game ends with a tie on victory points AND each of its battlefields will end with sides switching the win rounds (assumption: battlefields reward the same victory points) => in the game end, all armies will have the same victory points scored... the game ended with a tie BUT each player is being checked against their stakes in the respective battlefield they participated and if they won they can withdraw their stake. If they loose in the battlefield they'll be given 0 stake back.
