### ISSUE TITLE
Alternate frontend framework implementations

### ISSUE THREAD

**Issue by poroburu** [1337-Society/blotto#8]
As Blotto is a minimal intermediate app. I figure it could be a reference for making Cosmwasm dapps in frontend frameworks other than React/Next. The React/Next implementation can remain the canonical development nexus.

Myself, I want to make a port to Blazor. For example, it could be a useful library to wrap Cosmology components into Blazor Components.

**Comment by ismellike** [comment]
Blazor is great, and I'd love to see an example for the cosmos stack!

**Comment by JakeHartnell** [comment]
Now using tailwind.
